version: '3.8'

services:
  container-backup:
    image: container-backup:latest
    container_name: container-backup
    hostname: container-backup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro                             # Read-only access to Docker socket
      - /mnt/backups:/backups:rw                                                 # Persistent backup storage
      - /mnt/docker/container-backup/config:/app/config                          # Configuration files
    environment:
      - TZ=${TZ:-America/Denver}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - BACKUP_DIR=/backups
      - MAX_CONCURRENT_BACKUPS=${MAX_CONCURRENT_BACKUPS:-3}
      - BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS:-7}
      - PORTAINER_URL=${PORTAINER_URL}
      - PORTAINER_API_KEY=${PORTAINER_API_KEY}
      - PORTAINER_INSECURE=${PORTAINER_INSECURE:-false}
      - CONFIG_FILE=/app/config/service_configs.json
      - EXCLUDE_FROM_BACKUP=${EXCLUDE_FROM_BACKUP}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/backups') else 1)"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s

